version: '3.2'
services:
  product_db:
    image: postgres:14.6-alpine
    container_name: product_database
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=product_service
      - POSTGRES_PASSWORD=product 
      - PGDATA=/data/postgres
      - POSTGRES_DB=product
    networks:
      - product_network
    volumes:
      - ./product_volume:/var/lib/postgresql
  product_service:
    container_name: product_service
    build: 
      context: product-service
    ports: 
      - '127.0.0.1:8000:8000'  
    depends_on:
      - product_db
    environment:
      - DATABASE_URI=postgresql+psycopg2://product_service:product@product_db:5432/product
      - MODE=production
      - PATH=/directory/bin:$PATH
    networks:
      - product_network
    restart: unless-stopped
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - product_service
    container_name: proxy
    networks:
      - product_network
      - client_network
    restart: always
  client:
    build:
      context: client 
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./client/web_server.conf:/etc/nginx/conf.d/default.conf
    environment:
      - API_SERVER=http://proxy/v1/
    depends_on:
      - proxy
    container_name: client
    networks:
      - client_network
networks:
  product_network:
    driver : bridge
  client_network:
    driver : bridge

volumes:
  product_volume:
