version: '3.2'

services:
  product_db:
    image: postgres:14.6-alpine
    container_name: product_database
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=product_service
      - POSTGRES_PASSWORD=product 
      - PGDATA=/data/postgres
      - POSTGRES_DB=product
    networks:
      - product_network
  product_service:
    container_name: product_service
    build: 
      context: product-service
    ports: 
      - '8000:8000'  
    depends_on:
      - product_db
    environment:
      - DATABASE_URI=postgresql+psycopg2://product_service:product@product_db:5432/product
      - MODE=production
      - PATH=/directory/bin:$PATH
    command: "python3 main.py"
    networks:
      - product_network

networks:
  product_network:
    driver : bridge