"""init migration

Revision ID: 5d54501e6d82
Revises: 
Create Date: 2023-01-21 18:20:56.722257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d54501e6d82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('productID', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isFavorite', sa.Boolean(), nullable=True),
    sa.Column('isFlashSale', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=150), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('discount_type', sa.Enum('currency', 'percentage', name='type_of_discount'), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('productLegal', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('productID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
